### PR TITLE
Remove 'wso2-public' repository

### PR DESCRIPTION
**Pull request by makubi**
Remove the repository to fetch artifacts from Maven central directly.
Add second release and snapshot WSO2 repositories.

### CODE REVIEW

**Comment by kasunbg** [comment]
@makubi wso2-public is a proxy repository that proxies the maven central and bunch of other must-needed maven repos.
If we remove wso2-public, then the downstream projects will have to add those (must-needed) repos manually to their pom.

I'm not sure whether we want to do it at this point. What is the problem we are trying to fix here?

Thanks.

**Comment by makubi** [comment]
The problem is that downloading artifacts from the wso2-public is slow (about 10 kB/s) compared to the Maven Central repository.

Best would be to introduce a repository that contains all published artifacts by WSO2 and include it in the POM.

**Comment by kasunbg** [comment]
@makubi Thank you for getting this to our attention. I will raise an issue with wso2 infrastructure team on this.

I think fixing the slowness is the best approach to fix this issue. Btw, we have had our Jenkins daily jobs that was exhausting the nexus to its fullest. We just stopped doing that just last week.

Do you mind doing another quick test and see whether you see an improvement? Further, may I know from which region you are trying to access this from?

Thanks.

**Comment by makubi** [comment]
@kasunbg Thank you very much.

This will help as well, true, but you could remove the round-trip and enable the Maven Central repository additionally.

Tested it 2 days ago and just now once again. Still slow download and high ping times.
I am trying to access it from Germany.

Thanks

**Comment by chamarat-wso2** [comment]
@makubi , Can you send us following information in order to check the download slowness.

traceroute 52.220.154.241
traceroute 52.220.154.241  -I
mtr 52.220.154.241

Thanks,

**Comment by makubi** [comment]
@chamarat-wso2 Here are the outputs for

- traceroute: https://paste.coding4.coffee/?cd4f937dbde5b8d2#YFxaX44uznrU2LvB1Ht6lbrM3D7yNSmqH1JaHgKri7s=
- traceroute-I: https://paste.coding4.coffee/?a7c4178e120f5b99#j6/3A4rO4ZJFDpAsGPj7WUKqRYfLggY51Kxc/ZqdGC4=
- mtr -c 10: https://paste.coding4.coffee/?fa69fe3d346bfad0#alEViz8noo7pg1GYrQNAiNIG5Tu9kPdZiVJ/JCMJmWA=

**Comment by chamarat-wso2** [comment]
From the traceroute  we could see sudden increase in RTT from  one point ( 12 ae-6.r21.sngpsi05.sg.bb.gin.ntt.net (129.250.7.65) 273.041 ms 272.393 ms 272.476 ms ) hop  which increases til the destination.  This can causes slowness due to packet loss. You can try to access with another ISP or you need to inform this to your ISP, most of the time ISPs can choose best routing path for you.

**Comment by makubi** [comment]
I tried it with different ISPs. The problem is that the repository is only hosted in another part of the world (Singapore) and not additionally in Europe.

**Comment by Kishanthan** [comment]
@kasunbg , please review and merge/close this.

**Comment by kasunbg** [comment]
@makubi We now add wso2 artifacts to Maven Central since November! So, this issue should not be there now! Thanks for reporting.

[1] http://search.maven.org/#search%7Cga%7C1%7Corg.wso2.carbon

**Pull request closed without merging**
